import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/guards";
import { Role } from "@prisma/client";
import { ProgressBar } from "@/components/ProgressBar";
export default async function Gradebook(){
  const s=await requireRole(Role.STUDENT);
  const rows=await prisma.attempt.findMany({where:{studentId:s.id,status:{in:["SUBMITTED","AUTO_SUBMITTED"]}},include:{exam:{include:{course:true}}},orderBy:{submittedAt:"desc"}});
  const weighted=rows.filter(r=>r.score!=null&&r.exam.weight>0); const weightSum=weighted.reduce((a,r)=>a+r.exam.weight,0); const avg=weightSum?weighted.reduce((a,r)=>a+(r.score||0)*r.exam.weight,0)/weightSum:0;
  return <div className="container-page fade-in"><h1 className="text-3xl font-bold">Sổ điểm</h1><p className="text-slate-500 mt-2">Điểm trung bình dùng trọng số của từng đề, phù hợp cho 15 phút / giữa kỳ / cuối kỳ.</p><div className="grid md:grid-cols-3 gap-4 mt-6"><div className="card p-5"><div className="text-sm text-slate-500">Điểm trung bình có trọng số</div><div className="text-3xl font-bold mt-2">{avg.toFixed(2)}</div></div><div className="card p-5"><div className="text-sm text-slate-500">Số bài đã chấm</div><div className="text-3xl font-bold mt-2">{rows.length}</div></div><div className="card p-5"><div className="text-sm text-slate-500">Tiến độ điểm</div><div className="mt-3"><ProgressBar value={avg*10}/></div><div className="text-xs text-slate-400 mt-2">{Math.round(avg*10)}% thang điểm 10</div></div></div><div className="card mt-5 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="text-left p-4">Bài kiểm tra</th><th className="text-left p-4">Danh mục</th><th className="text-left p-4">Trọng số</th><th className="text-left p-4">Ngày nộp</th><th className="text-right p-4">Điểm</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="p-4 font-medium">{r.exam.title}<div className="text-xs text-slate-400">{r.exam.course.title}</div></td><td className="p-4">{r.exam.category}</td><td className="p-4">{r.exam.weight}×</td><td className="p-4">{r.submittedAt?.toLocaleString("vi-VN")}</td><td className="p-4 text-right font-bold">{r.score?.toFixed(1)}/10</td></tr>)}</tbody></table></div></div>
}
